version: '3.8'

services:
  app_blue:
    image: yongjun0511/clokey-docker:${TAG}
    container_name: app_blue
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=blue
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_URL=${DB_URL}
    networks:
      - app_network

  app_green:
    image: yongjun0511/clokey-docker:${TAG}
    container_name: app_green
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=green
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_URL=${DB_URL}
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
