version: '3.8'

services:
  app_blue:
    image: yongjun0511/clokey-docker:${TAG}
    container_name: app_blue
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=blue
    env_file:
      - .env  # .env 파일을 통해 환경 변수 로드
    networks:
      - app_network

  app_green:
    image: yongjun0511/clokey-docker:${TAG}
    container_name: app_green
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=green
    env_file:
      - .env  # .env 파일을 통해 환경 변수 로드
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
