version: '3.8'

services:
  app_blue:
    image: yongjun0511/clokey-docker:develop-latest
    container_name: app_blue
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=blue
    volumes:
      - ./src/main/resources/application-secret.yml:/app/config/application-secret.yml  # application-secret.yml 파일 마운트
    networks:
      - app_network

  app_green:
    image: yongjun0511/clokey-docker:develop-latest
    container_name: app_green
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=green
    volumes:
      - ./src/main/resources/application-secret.yml:/app/config/application-secret.yml  # 동일하게 마운트
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
