version: '3.8'

services:
  app_blue:
    image: yongjun0511/clokey-docker:${TAG}
    container_name: app_blue
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=blue
      - SPRING_DATASOURCE_URL=${DB_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
    env_file:
      - .env
    networks:
      - app_network
    depends_on:
      - mysql  # MySQL 서비스가 시작된 후 app_blue 시작

  app_green:
    image: yongjun0511/clokey-docker:${TAG}
    container_name: app_green
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=green
      - SPRING_DATASOURCE_URL=${DB_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
    env_file:
      - .env
    networks:
      - app_network
    depends_on:
      - mysql  # MySQL 서비스가 시작된 후 app_green 시작

  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      MYSQL_DATABASE=clokeydb
    ports:
      - "3306:3306"  # MySQL 포트
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
