## Default profile
spring:
  application:
    name: clokey
  profiles:
    group:
      "local": "local, jwt, oauth-local"
      "dev": "dev, jwt, oauth-dev"
    active: dev
  thymeleaf:
    enabled: true
springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: alpha
  use-fqn: true
---
# Local Profile
spring:
  config:
    activate:
      on-profile: local
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PW}
    url: ${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000
---
# Dev Profile
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PW}
    url: ${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000

logging:
  level.org:
    hibernate.SQL: DEBUG
    type.descriptor.sql.BasicBinder: TRACE
server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true



jwt:
  secret: ${JWT_SECRET_KEY}
  expiration: 86400000 # 1일 (밀리초 단위)


