name: CI/CD Pipeline

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set TAG as develop-latest
        run: echo "TAG=develop-latest" >> $GITHUB_ENV  # TAG를 환경 변수로 설정

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle Wrapper
        run: |
          ./gradlew --stop && ./gradlew clean --refresh-dependencies
          ./gradlew clean build
          ls -l build/libs

      - name: Build Docker Image
        run: |
          docker build -t youngjun0511/clokey-docker:${{ env.TAG }} .  # 환경 변수 TAG 사용

      - name: Push Docker Image
        run: |
          docker tag youngjun0511/clokey-docker:${{ env.TAG }} youngjun0511/clokey-docker:${{ env.TAG }}
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          docker push youngjun0511/clokey-docker:${{ env.TAG }}  # 환경 변수 TAG 사용

      - name: Copy docker-compose file to remote
        uses: appleboy/scp-action@v0.1.3
        with:
          username: ubuntu
          host: ${{ secrets.EC2_HOST }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "./docker-compose.yml"
          target: "/home/ubuntu/cicd/"

      - name: Deploy Blue-Green
        uses: appleboy/ssh-action@master
        with:
          username: ubuntu
          host: ${{ secrets.EC2_HOST }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/cicd
            
            # Determine current active color
            if docker-compose -f docker-compose.yml ps | grep app_blue; then
              TARGET=green
              OLD=blue
            else
              TARGET=blue
              OLD=green
            fi
            
            # Update target group
            docker-compose -f docker-compose.yml up -d app_$TARGET
            
            # Stop the old group after ensuring new group is running
            sleep 10
            docker-compose -f docker-compose.yml down app_$OLD

      - name: SSH to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            whoami
            ls -al

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: cicdsample
          path: ./build/libs/*.jar

      - name: Copy jar file to remote
        uses: appleboy/scp-action@v0.1.3
        with:
          username: ubuntu
          host: ${{ secrets.EC2_HOST }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "./build/libs/*.jar"
          target: "/home/ubuntu/cicd"
          debug: true

      - name: Execute deploy script
        uses: appleboy/ssh-action@master
        with:
          username: ubuntu
          host: ${{ secrets.EC2_HOST }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script_stop: true
          script: |
            if [ ! -f /home/ubuntu/cicd/deploy.sh ]; then
              echo "Error: deploy.sh not found on remote server!"
              exit 1
            fi
            chmod +x /home/ubuntu/cicd/deploy.sh
            sh /home/ubuntu/cicd/deploy.sh

