name: deploy

on:
  pull_request:
    branches:
      - develop  # PR이 master 브랜치로 merge될 때 트리거

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Copy deployment files via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: build/libs/*.jar  # 다른 파일만 복사
          target: ${{ secrets.EC2_DEPLOY_PATH }}  # EC2 서버에 복사할 대상 경로

      - name: Execute deploy script via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ${{ secrets.EC2_DEPLOY_PATH }}
            chmod +x ${{ secrets.EC2_DEPLOY_PATH }}/deploy.sh
            ./${{ secrets.EC2_DEPLOY_PATH }}/deploy.sh
